import Foundation

/// Claude Code'un (ve fork'larının) konuşmaya user rolüyle eklediği, kullanıcının
/// yazmadığı kayıtlar: slash komut zarfları (`<command-name>/clear</command-name>…`),
/// yerel komut çıktıları, system-reminder, arka plan görev bildirimleri, kesme ve
/// compact notları. Transcript'e düşerler ama chat'te kullanıcı mesajı değildirler
/// (karar 95, orca `harness-injected-user-turns.ts` + `native-chat-command-envelope.ts`).
///
/// Yalnız harness'ten GÖZLEMLENMİŞ etiket ve önekler eşlenir: `<my-element>` ile
/// başlayan gerçek bir istem kullanıcı turu olarak kalır.
public enum HarnessInjectedTurn {
    /// Slash komut zarfı: `<command-name>/x</command-name>…<command-args>…`.
    public struct CommandEnvelope: Sendable, Equatable {
        public let name: String
        public let args: String

        /// Kullanıcının yazdığı biçim: `/name args`.
        public var typedText: String {
            let short = name.hasPrefix("/") ? String(name.dropFirst()) : name
            // Plugin skill'i `/plugin:name` olarak kanonikleşir; kullanıcı kısa adı yazdı.
            let token = "/" + (short.split(separator: ":").last.map(String.init) ?? short)
            return args.isEmpty ? token : "\(token) \(args)"
        }
    }

    /// Claude Code'un yerleşik komutları: zarfı tamamen gizlenir (`/clear`,
    /// `/model` … kullanıcıya chat mesajı olarak gösterilmez). Listede olmayan
    /// komut (skill / özel komut) kullanıcının turu sayılır ve `/name args` olarak
    /// görünür — yoksa asistan boş bir konuşmaya cevap veriyormuş gibi görünür.
    static let builtInCommands: Set<String> = [
        "add-dir", "agents", "bug", "clear", "compact", "config", "context", "cost",
        "doctor", "effort", "exit", "export", "fast", "help", "hooks", "ide", "init",
        "login", "logout", "mcp", "memory", "model", "permissions", "plugin", "quit",
        "release-notes", "resume", "rewind", "status", "statusline", "terminal-setup",
        "theme", "upgrade", "usage", "vim",
    ]

    static let knownTagNames: Set<String> = [
        "agent-message", "bash-input", "bash-stderr", "bash-stdout",
        "command-args", "command-message", "command-name", "cross-session-message",
        "fork-boilerplate", "local-command-caveat", "local-command-stderr",
        "local-command-stdout", "mcp-polling-update", "mcp-resource-update",
        "system-reminder", "task-notification", "teammate-message",
        "user-memory-input", "user-prompt-submit-hook",
    ]

    static let injectedPrefixes = [
        "<channel source=",
        "[request interrupted",
        "a message arrived from ",
        "another claude session sent a message",
        "no response requested.",
        "caveat: the messages below were generated by the user while running local commands",
        "this session is being continued from a previous conversation",
    ]

    /// Sınıflandırma yalnız baş kısma bakar — çok KB'lık yapıştırmalarda O(1).
    private static let headLimit = 256

    /// Kullanıcı turu metni için chat'te gösterilecek hâl: `nil` = gizle,
    /// aksi hâlde gösterilecek metin (skill zarfı `/name args`'a çevrilir,
    /// sıradan metin aynen döner).
    public static func displayText(forUserText text: String) -> String? {
        if let envelope = commandEnvelope(text) {
            let short = envelope.name.hasPrefix("/") ? String(envelope.name.dropFirst()) : envelope.name
            return builtInCommands.contains(short.lowercased()) ? nil : envelope.typedText
        }
        return isInjected(text) ? nil : text
    }

    /// Yalnız gözlemlenmiş harness biçimleri için `true`.
    public static func isInjected(_ text: String) -> Bool {
        let head = normalizedHead(text)
        guard !head.isEmpty else { return false }
        if let tag = leadingTagName(head), knownTagNames.contains(tag) { return true }
        return injectedPrefixes.contains { head.hasPrefix($0) }
    }

    /// Zarf etiketiyle başlamayan metin (sıradan istem, XML yapıştırması) için `nil`.
    public static func commandEnvelope(_ text: String) -> CommandEnvelope? {
        let trimmed = text.drop(while: { $0.isWhitespace })
        guard trimmed.lowercased().hasPrefix("<command-"),
              let name = tagContent("command-name", in: trimmed)?
                .trimmingCharacters(in: .whitespacesAndNewlines),
              !name.isEmpty else { return nil }
        let args = tagContent("command-args", in: trimmed)?
            .trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
        return CommandEnvelope(name: name, args: args)
    }

    private static func tagContent(_ tag: String, in text: Substring) -> String? {
        guard let open = text.range(of: "<\(tag)>"),
              let close = text.range(of: "</\(tag)>", range: open.upperBound..<text.endIndex)
        else { return nil }
        return String(text[open.upperBound..<close.lowerBound])
    }

    private static func normalizedHead(_ text: String) -> String {
        String(text.drop(while: { $0.isWhitespace }).prefix(headLimit)).lowercased()
    }

    /// `<tag` ardından boşluk, `>` ya da metin sonu gelirse etiket adı.
    private static func leadingTagName(_ head: String) -> String? {
        guard head.hasPrefix("<") else { return nil }
        let name = head.dropFirst().prefix { $0.isLetter || $0.isNumber || $0 == "-" }
        guard let first = name.first, first.isLetter, first.isLowercase else { return nil }
        let rest = head.dropFirst(1 + name.count)
        guard rest.isEmpty || rest.first == ">" || rest.first?.isWhitespace == true else { return nil }
        return String(name)
    }
}
